---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: coredns
  namespace: kube-system
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://coredns.github.io/helm
      chart: coredns
      version: 1.8.4
      sourceRef:
        kind: HelmRepository
        name: coredns-charts
        namespace: flux-system
      interval: 5m
  values:
    replicaCount: 3
    serviceType: LoadBalancer
    prometheus:
      service:
        enabled: true
      monitor:
        enabled: true
    service:
      externalTrafficPolicy: Local
      loadBalancerIP: 10.0.6.99
      annotations:
        metallb.universe.tf/allow-shared-ip: coredns
    affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
                - key: app.kubernetes.io/name
                  operator: In
                  values:
                    - coredns
            topologyKey: "kubernetes.io/hostname"
    tolerations:
      - key: "arm"
        operator: "Exists"
    rbac:
      create: true
    isClusterService: false
    servers:
      - zones:
          - zone: york.haus.
            scheme: dns://
            use_tcp: false
        port: 53
        plugins:
          - name: errors
          - name: health
            configBlock: |-
              lameduck 5s
          - name: ready
          # - name: kubernetes
          #   parameters: cluster.local in-addr.arpa ip6.arpa
          #   configBlock: |-
          #     pods insecure
          #     fallthrough in-addr.arpa ip6.arpa
          #     ttl 30
          - name: prometheus
            parameters: 0.0.0.0:9153
          - name: forward
            parameters: . /etc/resolv.conf
          - name: cache
            parameters: 30
          - name: loop
          - name: reload
          - name: loadbalance
          - name: file
            parameters: /etc/coredns/york.haus
    zoneFiles:
      - filename: york.haus
        domain: york.haus
        contents: |
          york.haus.   IN SOA etta.ns.cloudflare.com. dns.cloudflare.com. 2020100600 10000 2400 604800 3600
          k3s.york.haus. IN A 172.29.240.100
          *.york.haus. IN A   172.29.240.1
          york.haus. IN A   172.29.240.1
