---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: coredns-charts
  namespace: flux-system
spec:
  interval: 10m
  url: https://github.com/coredns/coredns
  timeout: 3m
