---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: plex
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: plex
      version: 6.0.1
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: ghcr.io/k8s-at-home/plex
    env:
      TZ: "America/Chicago"
    podSecurityContext:
      supplementalGroups:
        - 44
        - 109
        - 100
    service:
      main:
        type: LoadBalancer
        loadBalancerIP: 172.29.243.99
        externalTrafficPolicy: Local
        annotations:
          metallb.universe.tf/allow-shared-ip: plex
        primary: true
        ports:
          http:
            port: 32400
      dnla-tcp:
        enabled: false
        type: NodePort
        ports:
          dnla-tcp:
            enabled: true
            port: 32469
            protocol: TCP
            targetPort: 32469
        externalTrafficPolicy: Local
      dnla-udp:
        enabled: false
        type: NodePort
        ports:
          dnla-udp:
            enabled: true
            port: 1900
            protocol: TCP
            targetPort: 1900
        externalTrafficPolicy: Local
    persistence:
      config:
        enabled: true
        storageClass: "config-data"
        accessMode: ReadWriteOnce
        size: 20Gi
      transcode:
        enabled: true
        type: emptyDir
        medium: Memory
      tmp:
        enabled: true
        type: emptyDir
        medium: Memory
      nfs-media-pvc:
        enabled: true
        existingClaim: nfs-media-pvc
        mountPath: /data
        readOnly: false
    podAnnotations:
      backup.velero.io/backup-volumes: config
    resources:
      requests:
        cpu: 2000m
        memory: 1500Mi
      limits:
        memory: 4900Mi
    addons:
      promtail:
        enabled: true
        image:
          repository: grafana/promtail
          tag: 2.9.10
        loki: http://loki.logs.svc.cluster.local:3100/loki/api/v1/push
        logs:
          - name: promtail/plex
            path: "/config/Library/Application Support/Plex Media Server/Logs/*.log"
          - name: promtail/plex/plugins
            path: "/config/Library/Application Support/Plex Media Server/Logs/PMS Plugin Logs/*.log"
        volumeMounts:
          - name: config
            mountPath: /config
            readOnly: true
        securityContext:
          runAsUser: 0
  valuesFrom:
    - kind: Secret
      name: "plex-helm-values"
      optional: false
