---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ambassador-operator
  namespace: ambassador
spec:
  interval: 5m
  dependsOn:
    - name: vault-secrets-operator
  chart:
    spec:
      chart: ambassador-operator
      version: 0.3.0
      sourceRef:
        kind: HelmRepository
        name: ambassador-charts
        namespace: flux-system
      interval: 5m
  values:
