---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: registry-creds-leader-election-role
  namespace: kube-system
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
    resourceNames:
      - 8bdecb1a.alexellis.io
    verbs:
      - get
      - create
      - update
      - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: registry-creds-registry-creds-role
rules:
  - apiGroups:
      - ""
    resources:
      - namespaces
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - create
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - serviceaccounts
    verbs:
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - ops.alexellis.io
    resources:
      - clusterpullsecrets
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: registry-creds-leader-election-rolebinding
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: registry-creds-leader-election-role
subjects:
  - kind: ServiceAccount
    name: default
    namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: registry-creds-registry-creds-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: registry-creds-registry-creds-role
subjects:
  - kind: ServiceAccount
    name: default
    namespace: kube-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    control-plane: registry-creds-controller
  name: registry-creds-registry-creds-controller
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      control-plane: registry-creds-controller
  template:
    metadata:
      labels:
        control-plane: registry-creds-controller
    spec:
      containers:
        - args:
            - --enable-leader-election
          command:
            - /controller
          image: ghcr.io/alexellis/registry-creds:0.2.7
          imagePullPolicy: IfNotPresent
          name: controller
          resources:
            limits:
              memory: 200Mi
            requests:
              cpu: 100m
              memory: 45Mi
      terminationGracePeriodSeconds: 10
      tolerations:
        - key: arm
          operator: Exists
