---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: node-red
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: node-red
      version: 10.3.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: nodered/node-red
      tag: 2.0.6-12-minimal
    env:
      TZ: "America/Chicago"
      FLOWS: "flows.json"
      NODE_RED_ENABLE_PROJECTS: "true"
      NODE_RED_ENABLE_SAFE_MODE: "false"
    persistence:
      data:
        enabled: true
        mountPath: /data
        storageClass: "config-data"
        accessMode: ReadWriteOnce
        size: "5Gi"
    podAnnotations:
      backup.velero.io/backup-volumes: data
    tolerations:
      - key: "arm"
        operator: "Exists"
    resources:
      requests:
        memory: 350Mi
        cpu: 25m
      limits:
        memory: 500Mi
