apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-config-pv
spec:
  storageClassName: config-data
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 172.29.236.29
    path: "/containers"
  mountOptions:
    - nfsvers=4
    - tcp
    - intr
    - hard
    - noatime
    - nodiratime
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-data-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: config-data
  resources:
    requests:
      storage: 1Mi
