apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-external-provisioner-db
provisioner: k8s-sigs.io/nfs-subdir-external-provisioner-db # or choose another name, must match deployment's env PROVISIONER_NAME'
parameters:
  archiveOnDelete: "false"

---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-external-provisioner-config
provisioner: k8s-sigs.io/nfs-subdir-external-provisioner-containers # or choose another name, must match deployment's env PROVISIONER_NAME'
parameters:
  pathPattern: "${.PVC.namespace}/${.PVC.annotations.nfs.io/storage-path}"
  archiveOnDelete: "false"
