---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: readarr
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: readarr
      version: 6.0.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: ghcr.io/k8s-at-home/readarr
      tag: v0.1.0.963
    env:
      TZ: "America/Chicago"
      # PUID: 1001
      # PGID: 1001
    ingress:
      main:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: "ambassador"
        hosts:
          - host: readarr.york.haus
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "readarr.york.haus"
    podAnnotations:
      backup.velero.io/backup-volumes: config
    persistence:
      config:
        enabled: true
        storageClass: "rook-ceph-block"
        size: 2Gi
      media:
        enabled: true
        existingClaim: nfs-media-pvc
    podSecurityContext:
      runAsUser: 1001
      runAsGroup: 1001
      fsGroup: 1001
    resources:
      requests:
        memory: 350Mi
        cpu: 25m
      limits:
        memory: 500Mi
    tolerations:
      - key: "arm"
        operator: "Exists"
