apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: external-minio
  annotations:
    kubernetes.io/ingress.class: ambassador
spec:
  rules:
    - host: minio.york.haus
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: external-minio
                port:
                  number: 9000
  tls:
    - hosts:
        - minio.york.haus
---
apiVersion: v1
kind: Service
metadata:
  name: external-minio
spec:
  ports:
    - name: minio
      port: 9000
  type: ExternalName
  externalName: truenas
