apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: external-truenas
  annotations:
    kubernetes.io/ingress.class: ambassador
spec:
  rules:
    - host: truenas.york.haus
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: external-truenas
                port:
                  number: 443
  tls:
    - hosts:
        - truenas.york.haus
---
apiVersion: v1
kind: Service
metadata:
  name: external-truenas
spec:
  ports:
    - name: https
      port: 443
  type: ExternalName
  externalName: truenas
