apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: external-nvr
  annotations:
    kubernetes.io/ingress.class: ambassador
spec:
  rules:
    - host: nvr.york.haus
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: external-nvr
                port:
                  number: 81
  tls:
    - hosts:
        - nvr.york.haus
---
apiVersion: v1
kind: Service
metadata:
  name: external-nvr
spec:
  ports:
    - name: http
      port: 81
  type: ExternalName
  externalName: nvr
