---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metallb
  namespace: kube-system
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://metallb.github.io/metallb
      chart: metallb
      version: 0.10.2
      sourceRef:
        kind: HelmRepository
        name: metallb-charts
        namespace: flux-system
      interval: 5m
  values:
    configInline:
      peers:
        - peer-address: 172.29.236.1
          peer-asn: 64512
          my-asn: 64512
      address-pools:
        - name: layer2
          protocol: layer2
          addresses:
            - 172.29.243.1-172.29.243.254
          avoid-buggy-ips: true
    prometheusRule:
      enabled: true
    prometheus:
      enabled: true
      serviceMonitor:
        enabled: true
      prometheusRule:
        enabled: true
    controller:
      # image:
      #   repository: quay.io/metallb/controller
      #   tag: v0.10.1
      tolerations:
        - key: "arm"
          operator: "Exists"
    speaker:
      # image:
      #   repository: quay.io/metallb/speaker
      #   tag: v0.10.1
      tolerations:
        - key: "arm"
          operator: "Exists"
        - key: "armhf"
          operator: "Exists"
        - key: "node-role.kubernetes.io/master"
          operator: "Exists"
